### ISSUE TITLE
TS 26.532: Clarification on reportFormat URIs for reports defined in the spec

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#111]
TS 26.532 v18.1.0 Table 5.4.2.2-1 shows that a *DataReportingRule* has a mandatory `reportingFormat` property which contains a URI describing the report format to use.

I cannot seem to find the reportingFormat URIs to use for the base data report types defined in TS 26.532. Table 7.3.2.3-1 defines the actual report structure, and Annex A defines the record types, but the reportFormat URIs are not stated in either location. Are these reportingFormat URIs defined anywhere?

**Comment by rjb1000** [comment]
My assessment is that the reporting format for any given data domain is pre-determined by the JSON data types defined in TS 26.532 table 7.3.2.3-1. (This view is further supported by the text in clause 5.3.2.3.)

I believe this stems from a misinterpretation of the stage-2 requirement in TS 26.531 clauses 4.6.x which refer to the high-level concept of _reporting format_ in the context of _data reporting rules_. Because this requirement is implicitly satisfied by the JSON syntax in TS 26.532 table 7.3.2.3-1, it was a mistake to express this as an explicit property of _DataReportingRule_ in table 5.4.2.2-1.

In light of this, the _reportingFormat_ property appears to be redundant and I recommend removing it altogether from table 5.4.2.2-1 (and from the OpenAPI), taking care to remove all other references to reporting format in other rows of this table.

**Comment by rjb1000** [comment]
Given that this issue affects the reporting of UE data to the standalone Data Collection AF (i.e. for exposure of the basic SA2 events to NWDAF), I think changes to both Rel-17 and Rel-18 are justified, even though 5G-MAG Reference Tools is only implementing Rel-18.

The Rel-17 fix could potentially be folded in to TS 26.532 CR0007 that is already addressing #114.

**Comment by rjb1000** [comment]
For reasons of backwards compatibility, we could simply mark the property as optional.

It could be marked as deprecated in Rel-17.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
    Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
