### ISSUE TITLE
Reference to ROM in TS 26.346

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#12]
** Step 1: Describe the bug**
Clause 5.5.3 in TS 103 720 does not directly refer to TS 26.346, clause 5.2.3.1.1. It also does not mandate to set r14:romService to true. There are also mandates on using specific IP addresses and UDP ports.

** Step 2: Suggested solution **
Add this reference with some additional explanations and require r14:romService to be set to true.

** Step 3: Additional context**
ROM services are not related in the two specs.

** Step 4: Choose related standard/project (right side)
ETSI TS 103 720 second version

**Comment by rjb1000** [comment]
There appears to be a gap in TS 26.346 because the registration of the well-known multicast IP address and port with IANA was never concluded. MBMS ROM operation can't easily work without knowing the multicast IP address to join in order to receive the Service Announcement Channel.

At SA4#118-e, the Qualcomm rapporteur for TS 26.346 raised this issue in the following contribution: [S4-220416](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_118-e/Docs/S4-220416.zip).

Apparently, it had fallen through the cracks after the IANA reviewer pushed back on the idea of reserving an IP address in the Source-Specific Multicast (SSM) range.

A possible solution under consideration by SA4 is to instead attempt to reserve an IP address from the *Any-Source Multicast (ASM)* range. Something very similar was successfully achieved by DVB in 2008 to support IPTV SD&S server discovery (see IETF [RFC 5328](https://datatracker.ietf.org/doc/html/rfc5328)) and the [DVB Native IP specification](https://dvb.org/?standard=native-ip-broadcasting) reuses the same reserved address for discovering the bootstrap service announcement channel in DVB BlueBook A180, _viz:_

> ### 8.2.2 IP Multicast Address and Port
> Signalling information shall be carried in the payload of IP multicast packets with a well-known IP address and UDP port number dedicated to this function. This address has been registered by DVB (dvbservdsc) with IANA described in IETF RFC 5328 [19] and is 224.0.23.14 for IPv4 and FF0X:0:0:0:0:0:0:12D for IPv6. The port number is 3937/udp.

**Comment by jordijoangimenez** [comment]
@haudiobe, @rjb1000, please check addition in clause 5.5.3 (https://member.5g-mag.com/wg/CD-T/document/779).
IANA details will have to wait unless there is an update on progress from SA4?

**Comment by rjb1000** [comment]
I can confirm that there has been no progress in SA4 on the IP address range allocation issue.

I suspect it has fallen through the cracks again, @haudiobe?

**Comment by jordijoangimenez** [comment]
Two new Issues for multicast ip:port have been created [#25](https://github.com/5G-MAG/Standards/issues/25) and [#26](https://github.com/5G-MAG/Standards/issues/26)

Issue 12 will be closed once we agree on the current proposal in [CPT0092](https://member.5g-mag.com/wg/CD-T/document/779)

**Comment by jordijoangimenez** [comment]
Adopted in https://member.5g-mag.com/wg/CD-T/document/779

Two new Issues for multicast ip:port have been created https://github.com/5G-MAG/Standards/issues/25 and https://github.com/5G-MAG/Standards/issues/26
