### ISSUE TITLE
Figure 4.2.2-1 vs Figure 5.2.1-1: if compared, it seems that MBMS GW is part of the RAN (since most implementations of MBMS-GW are within BMSC this might be confusing)

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#2]
**Description of the improvement:** 
Figure 4.2.2-1 vs Figure 5.2.1-1: if compared, it seems that MBMS GW is part of the RAN (since most implementations of MBMS-GW are within BMSC this might be confusing)

**Context:** 
Figure 4.2.2-1 shows the reference architecture for 5G Broadcast System, including parts NodeB and Application and Core Network
Figure 5.2.1-1 shows the reference architecture for 5G Broadcast System for linear TV and radio services with LTE-based 5G Broadcast instantiation including eNodeB, MBMSGW, MME BM-SC

It is not clear if MBMS-GW, MME and BM-SC in Figure 5.2.1-1 are part of the application and core network or the NodeB of Figure 4.2.2-1.

**Suggested solution:**
Indicate within the text which parts in Figure 5.2.1-1 belong to which parts in Figure 4.2.2-1.

**Comment by rjb1000** [comment]
I believe that the MBMS-GW, MME and BM-SC are part of the Application and Core Network rather than part of the RAN ("NodeB") in the abstract architecture, but Thomas might correct me.

I agree that Figure 5.2.1-1 is ambiguous. It should be improved by adding a box labelled "Application and Core Network" that encloses the MBMS-GW, MME and BM-SC. This would then map the concrete instantiation back to the abstract model unambiguously.

**Comment by rjb1000** [comment]
@haudiobe prefers to leave figure 5.2.1-1 should be left unmodified.

The alternative remedy I suggest is to remove the box labelled "Application and Core Network" from figure 4.2.2-1 since this is never referred to from the text. As well as removing the ambiguity of the mapping from the abstract architecture to the concrete instantiation, it also simplifies the diagram.

**Comment by jordijoangimenez** [comment]
@haudiobe to update Figure 4.2.2-1, remove "core and application" block

**Comment by jordijoangimenez** [comment]
ACTION for @jordijoangimenez  to try Visio or liaise with @haudiobe

**Comment by johannmika** [comment]
Changed Figure 4.2.2-1, removed the box labelled "Application and Core Network"and uploaded here: https://member.5g-mag.com/wg/CD-T/document/779. 
@jordijoangimenez please check if ok.

**Comment by jordijoangimenez** [comment]
Please refer to; https://member.5g-mag.com/wg/CD-T/document/779

**Comment by rjb1000** [comment]
Replacement figure looks fine, @johannmika.

Editorially, however, we need to show this as a tracked change.

I also fixed that and another few minor typos in the editor's draft.

Result is uploaded to https://member.5g-mag.com/wg/CD-T/document/779 as V1.1.7.

**Comment by jordijoangimenez** [comment]
Thank you @rjb1000, I may had pasted the new figure from @johannmika without track changes.
