### ISSUE TITLE
Add additional xMB calls for a static configuration (probably not directly in TS 103 720)

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#3]
**Describe the bug**
xMB API not supporting static configuration of carriers/services.

**Suggested solution**
Enable static configuration via xMB, e.g.extend xMB API to
- get information about static configuration (GET) including carrier, bandwidth, totalDatarate, maxAvailableDatarate, and the following information per service: MCH, MCS, subframes, TBS, dataRate, TMGI
- change configuration (PATCH/PUT) including carrier, bandwidth, mbmsServiceAreas, MCH, MCS, allocated subframes, TBS.

**Additional context**
In my understanding, two modes are possible for carrier/service configuration in the BM-SC: (i) dynamic (using QCIs) and (ii) static configuration (setting a number of subframes, MCS per MCH, bandwidth, TBS,...). If broadcaster use HPHT transmission, they might need static/fixed transmission settings for guaranteed reception of their customers. Using dynamic configuration might lead to modulation (MCS) changes of existing services if a new service is added. 
Current BM-SC support static configuration already but not via xMB interface.

**Comment by rjb1000** [comment]
In terms of T-shirt size classification, this one feels "large".

**Comment by rjb1000** [comment]
On further discussion, it seems to me that the requirement for a low-level configuration interface is a genuine operational requirement, and could be appropriate for standardisation.

It was pointed out that the BM-SC does not deal with low-level transmission parameters, instead providing a higher level service abstraction. Exposing transmission parameters on xMB-C would require a lot of information to be passed up the chain of MBMS functions.

Moreover, these are not parameters that a Content Provider should be interested in. @johannmika clarified that the configuration interface is intended more for use by the Broadcast Network Operator. Since this is a logically separate role from the Content Provider, it seems more appropriate to use a different interface to configure the transmitter.

Recommendation is to investigate whether an existing 3GPP control plane interface offers the desired configuration. A quick glance through TS 23.246 suggests that neither the MBMS GW nor the MME deal with such low-level transmission parameters. Likewise, these concepts are not obviously present in the M3 Application Protocol (TS 34.66) either, which suggests that they are configured downstream in the eNodeB itself.

I recommend searching relevant eNodeB specifications for clues.

Failing that, it seems pretty unlikely that 3GPP would have the appetite to standardise a new configuration interface in the legacy eNodeB. It could be appropriate for ETSI JTC Broadcast to standardise such an interface (in theory, at least) for reasons of interoperability between transmitters from different vendors. In practice, though, it might be difficult to find anyone to do the work. So you might be stuck with a vendor-proprietary configuration interface.

**Comment by johannmika** [comment]
@rjb1000 I agree that most of the parameters will be more useful for the network operator. But I think MCS might make sense (as far as I understood, this is different to QCI (in "mc-extension" parameter) and there is no clear mapping between QCI and a fixed MCS). Here is more a use-case based description:

For 5G broadcast (standalone downlink only), a (fixed) MCS (Modulation Coding Scheme) has to be set, based on the receiving conditions of the users of the content provider. For example, if a broadcaster wants to transmit a 3 Mbps stream to his mobile users, the BC may prefer to use MCS9 (to maximize number of recipients). If his audience is rather slow/stationary he may use MCS26. Therefore it would make sense to allow the content provider the possibility to signal the maximum data rate and the MCS to be used to the BNO via xMB interface.
From a commercial point of view, the MCS and the maximum data rate ("max-ingest-bitrate") can then be used to calculate the required bandwidth in Hz (out of 8 MHz channel), which may then be charged to the content provider.

**Comment by rjb1000** [comment]
It seems legitimate for the Content Provider to have a preferred Modulation Coding Scheme in order to trade off the data rate against signal robustness and coverage radius. But it seems to me that it would be simpler to negotiate this through a written Service Level Agreement between the Content Provider and the Broadcast Network Operator. It's not a transmission parameter that would need to change dynamically.

Moreover, low-level transmission parameters are at a very different level of abstraction from the present xMB-C interface which deals in the currency of high-level service outcomes.

One possible solution would be for the MBMS System to determine the "best" (i.e. most robust) Modulation Coding Scheme to use based on the set of unoccupied radio channels currently available in the frequency plan and the maximum transport data rate requested by the Content Provider at xMB-C.

It would be interesting to find out how this was originally intended to work by asking @haudiobe. Some things are just deliberately left to implementation rather than standardisation.

**Comment by johannmika** [comment]
@rjb1000, thank you for your reply!

I agree that this can also be negotiated through a written SLA but the intention is to enable flexibility as much as possible for the content provider (i.e. using an API to determine if free resources can be used). 

For the Broadcast on Demand scenario it might be necessary for the content provider to dynamically provision a service and to decide for which kind of recipients the service should be available. 
The target for the broadcast network operator in this scenario is to ensure a maximum use of a broadcast channel, i.e., offer remaining unused (e.g. not used for 24/7) capacity to content providers which can then dynamically decide to use the broadcast path for the distribution to their clients (e.g. for events,...). 
If the BNO gets a request from the content provider the core should automatically check available resources and signal to the content provider an availability of resources via xMB. If resources are available, a service will be dynamically set up, including max bandwidth, desired MCS, starttime, endtime, path to the content,.... The content provider can then be charged based on those parameters.

I agree that low-level transmission parameters (like MCS) might be difficult to decide for the content provider. It would also m make sense to have a (long) list of possible use cases and indicate that to the core over xMB (e.g., "mobile reception in cars up to 100 km/h", "mobile reception in public transport") and the core/BNO maps that requirement to the required MCS based on his experience and infrastructure.

The suggested solution with the "best" (most robust) MCS might consume more bandwidth than needed and thus prevent more services to be added if the first one consumes all the unoccupied radio bandwidth of a channel. On the other hand, an agreed MCS for a service should not be changed because some recipients might loose the reception.

**Comment by jordijoangimenez** [comment]
Some aspects would require some previous 3GPP work before ETSI spec update. 
This will not be included in the next version of the ETSI spec
