### ISSUE TITLE
TS26.501 Clarification - Appropriate network entity for metrics error reports

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#66]
# Problem description
TS26.501 V17.5.0 clause 5.5.3 defines the required steps for AF-based metrics reporting. Step 8 of this procedure is defined as follows:

> The Media Player acknowledges its support for the collection of the required metrics of all configured schemes. If the request cannot be supported by the Media Player (e.g., inability to measure metrics according to one of the configured schemes), an **error message shall be sent by the Media Session Handler to the appropriate network entity**, indicating that metrics reporting for the indicated metrics scheme cannot be supported for this streaming service.

For me, it is not apparent what is meant by _appropriate network entity_. I assume the error report should be send to the list of 5GMS AF defined in the `ServiceAccessInformation.clientMetricsReportingConfigurations.serverAddresses` property?

# Suggested solution
It would be great if we can clarify what is meant by the above described statement. I might have missed something here. Moreover, during the 5G-MAG SA4 developers call the question popped up if this error report needs to be send at all.

# Related issues
* https://github.com/5G-MAG/rt-5gms-media-session-handler/issues/17

**Comment by rjb1000** [comment]
Looks like an inconsistency between this stage-2 specification in TS 26.501 and the stage-3 APIs specified in TS 26.512 where no endpoint is specified on the 5GMS AF for error reporting by the Media Session Handler.

Suggest we discuss with the SA4 experts to get their take on this.

What is the purpose of reporting an error if the configured metics reporting scheme cannot be supported by a Media Session Handler? There's not much that can be done about it, but maybe it's just good to know why no metrics reporting is happening?

Any early thoughts, @gheikkila, @haudiobe, @tlohmar?

**Comment by gheikkila** [comment]
In the last version (17.4.0) of 26.512 we did add some error reporting. I think the general idea of reporting errors is to at least allow some way for the configuring entity to get a feedback if the configuration isn't ok. Otherwise the MSH would just swallow it silently, and debugging on OAM level would be very difficult.

![image](https://github.com/5G-MAG/Standards/assets/7382690/f844d52a-d428-4c8a-b6d3-f1bbec89ffab)

**Comment by rjb1000** [comment]
> In the last version (17.4.0) of 26.512 we did add some error reporting. I think the general idea of reporting errors is to at least allow some way for the configuring entity to get a feedback if the configuration isn't ok. Otherwise the MSH would just swallow it silently, and debugging on OAM level would be very difficult.

Thanks for the memory jog, @gheikkila. Yes, you're right that we added the `ERROR_METRICS_REPORTING` error event to the M6 client API. Looking at figure 12.2.1-1, I think this is intended to be used by the Media Session Handler to notify the 5GMS-Aware Application that an attempt to send a metrics report has failed (e.g. because the server was unresponsive and the HTTP transaction timed out).

The error condition envisaged by the text cited from TS 26.501 clause 5.5.3 by @dsilhavy appears to be more to do with the Media Session Handler reporting an error to "the appropriate network entity" (which I read as "5GMSd AF") when the Media Player doesn't support one of the metrics reporting schemes mentioned in the client metrics reporting configuration of the Service Access Information.

There's definitely a big hole in TS 26.512 at reference point M5 in this regard: no way to report the error to the 5GMSd AF.

The key question for SA4 is whether we want to fill the gap in TS 26.512 or just remove the requirement from TS 26.501.

**Comment by rjb1000** [comment]
@fredericgabin: I will remove this from TS 26.501 to align stage-2 to stage-3.

**Comment by rjb1000** [comment]
CR contributed to SA4#125 by @fredericgabin:

* TS 26.501:
  * Rel-16: Not contributed.
  * Rel-17: **CR0072** "CR to 26.501-0072 on Stage 2 alignment (Rel-17)" in [S4-231132](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231132.zip).
  * Rel-18: Not contributed.

**Comment by rjb1000** [comment]
CR Packs approved at SA#101:
* TS 26.501
  * Rel-16: CR0076r2 "Clarifications to Network Assistance feature" in [SP-230914](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-230914.zip).
  * Rel-17: CR0075r3 "Clarifications to Network Assistance feature" in [SP-230914](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-230914.zip) (mirror of CR0076r2).
  * Rel-18: CR0066r5 "Clarifications to Network Assistance feature" in [SP-230919](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-230919.zip) (not an exact mirror CR).
