### ISSUE TITLE
TS26.512 - How to choose a address from clientConsumptionReportingConfiguration.serverAddresses array for consumption reporting

### ISSUE THREAD

**Issue by shilinding** [5G-MAG/Standards#71]
# Problem description
TS26.512-h40 clause 4.7.4, it says when there are AF addresses are listed in the `clientConsumptionReportingConfiguration.serverAddresses` array,  we choose one address to send report message. But how to choose one wasn't defined.

> In order to submit a consumption report, the Media Session Handler shall send an HTTP POST message to the 5GMSd AF. If several 5GMSd AF addresses are listed in the `clientConsumptionReportingConfiguration.serverAddresses` array (see table 11.2.3.1-1), the Media Session Handler **shall choose one and send the message to the selected**. The request body shall be a `ConsumptionReport` structure, as specified in clause 11.3.3.1. The server shall respond with a 200 (OK) message to acknowledge successful processing of the consumption report.

# Suggested solution
* Could we always choose the first one?
* Or generate a random valid value as the index of address?

**Comment by rjb1000** [comment]
Good question. I agree this is ambiguous in TS 26.512. It is unclear whether multiple server endpoints are signalled for the purpose of resilience or load balancing or both.

In the absence of a clear specification, this means that it is currently up to implementation choice.

# Resilience questions

If the server endpoint selected by the Media Session Handler fails to respond (after a small number of retry attempts), should it work its way through the remaining server endpoints listed in the `clientConsumptionReportingConfiguration.serverAddresses` array hoping for better luck?

# Load balancing questions
SA4 needs to consider whether it would be acceptable if all 5GMSd Clients selected the first server endpoint, or whether we need to be more prescriptive about the Media Session Handler picking one at random in order to spread the load.

And if the Media Session Handler is supposed to make a random choice of server endpoint, should it choose once at the start of each media streaming session, or should it make a (potentially different) random choice of endpoint for each consumption report it wants to send?

Alternatively, TS 26.512 could specify that the 5GMS AF randomises the server endpoints in the `clientConsumptionReportingConfiguration.serverAddresses` array in each request it receives at reference point M5d. Then it would be safe for the Media Session Handler to always pick the first one (and work through the array in the order the server endpoints appear for resilience).

**Comment by rjb1000** [comment]
Thanks for the background history, @gheikkila. If the primary motivation is load balancing, it would make sense to align with that for both QoE metrics reporting and consumption reporting.

* Is there any indication in TS 26.247 of whether the random selection between available server endpoints should be done once at the start of the session or every time a report needs to be sent? The text you cite above just says "with uniform distribution" which could be achieved with either approach, but it looks like this is left to implementation.
* Is there any sense of trying a different server endpoint if the first choice doesn't appear to be working?

**Comment by rjb1000** [comment]
CR contributed to SA4#125 by @rjb1000:

* TS 26.512
  * Rel-16: **CR0043** "Essential maintenance" in [S4-231158](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231158.zip).
  * Rel-17: **CR0037** "Essential maintenance" in [S4-231156](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231156.zip).

**Comment by rjb1000** [comment]
CRs agreed at SA4#125:

* TS 26.512
  * Rel-16: **CR0043**r1 "Essential maintenance" in [S4-231425](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231425.zip).
  * Rel-17: **CR0037**r2 "Essential maintenance" in [S4-231424](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231424.zip).

**Comment by rjb1000** [comment]
CRs revised (YAML corrections) and approved at SA#101:

* TS 26.512
  * Rel-16: **CR0043**r2 "Essential maintenance" in [SP-231082](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231082.zip).
  * Rel-17: **CR0037**r3 "Essential maintenance" in [SP-231053](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231053.zip).

**Comment by rjb1000** [comment]
Approved changes published and available for download:
* TS 26.512 [V16.11.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gb0.zip)
* TS 26.512 [V17.6.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h60.zip)
