### ISSUE TITLE
ETSI TS 103 720 V1.2.1 - Delivery of Warning Messages from MME to eNodeB

### ISSUE THREAD

**Issue by kuehnhammer** [5G-MAG/Standards#84]
# Context
5.15.1 Reference architecture specifies the end-to-end interfaces and delivery flow for warning messages, but has a gap between MME and eNodeB.

# Problem description
<img width="505" alt="image" src="https://github.com/5G-MAG/Standards/assets/1220339/82a64894-b369-4746-bdb9-b6802d25522b">

Figure 5.15.2-1 shows Write-Replace Warning Request/Response messages, which correspond to the Warning Message Transmission Procedures specified in interface S1AP (3GPP TS 36.413).

<img width="258" alt="image" src="https://github.com/5G-MAG/Standards/assets/1220339/11c1b46b-eed2-4c73-8091-b91c192440a0">

The S1 interface is the direct 1:n connection between MME and eNodeBs, but is not specified (nor otherwise useful or needed) in the reference architecture for LTE-based 5G Broadcast.

The existing connection from MME to eNodeB via the MCE (interfaces M3 and M2) has no comparable messages or procedures.

# Suggested solution
To be discussed.

Either:
- extend LTE-based 5G Broadcast architecture with a direct S1 interface between eNb and MME, possibly limiting its required implementation to Warning Message Transmission Procedures
- extend the M2 and M3 protocols to include similar procedures
- add a new interface

**Comment by rjb1000** [comment]
Better to add reference point **S1** to the reference architecture in figure 5.1.1-1 of TS 103 720, I think. The description of this reference point should indicate that only a subset of messages are relevant to PWS, per the procedures in clause 5.515.2 and as profiled in a new clause 5.15.3.2A. That new clause would list _Write-Replace Warning_ request/response as the relevant messages.

Then figure 5.15.1-1 could be modified to relabel **M3** as **S1**. The MCE would also need to be added per the suggestions on #83, but ghosted out since it plays no role in PWS deployments.

**Comment by dvargasparedero** [comment]
action from WG CD call:
- combine with #77
